#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# The compose file on main may not be compatible with the latest release.
#

name: pankeep

services:
  pankeep-server:
    container_name: pankeep_server
    image: dockertest
    ports:
      - '50322:22'
      - '56201:5901'
    restart: always
    healthcheck:
      disable: false